version: '3'
services:
  web-dvwa:
    container_name: web-dvwa
    image: vulnerables/web-dvwa
    ports:
      - "8080:80"
  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  elasticsearch:
    container_name: elasticsearch  
    image: elasticsearch:7.7.0
    hostname: elasticsearch
    environment: 
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
    networks: 
      - elknetwork
  kibana:
    container_name: kibana
    image: kibana:7.7.0
    hostname: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork
  logstash:
    container_name: logstash
    image: logstash:7.7.0
    hostname: logstash
    ports:
      - 9600:9600
      - 8089:8089
    volumes:
      # - ./logstash:/usr/share/logstash/pipeline/
      - ./logstash:/etc/logstash/conf.d
    links: 
      - elasticsearch:elasticsearch
    depends_on: 
      - elasticsearch
    networks: 
      - elknetwork
    

networks: 
  elknetwork:
    driver: bridge

volumes:
  portainer_data: {}


